"""add student profile fields

Revision ID: 52b8cfddbe1a
Revises: 67e6899c9e57
Create Date: 2026-03-11 20:23:15.552363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b8cfddbe1a'
down_revision: Union[str, None] = '67e6899c9e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('student_status', sa.String(), nullable=False, server_default='active_student'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('student_status')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('major')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('major')

    # ### end Alembic commands ###
