"""add confidence metrics to analysis

Revision ID: 67e6899c9e57
Revises: 98d2d89ab698
Create Date: 2026-03-03 21:25:33.239306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e6899c9e57'
down_revision: Union[str, None] = '98d2d89ab698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence_reasoning', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('confidence_reasoning')
        batch_op.drop_column('confidence_score')

    # ### end Alembic commands ###
