"""Add market_skills and gaps

Revision ID: 7969d5f0b142
Revises: 52b8cfddbe1a
Create Date: 2026-04-14 14:29:33.751229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7969d5f0b142'
down_revision: Union[str, None] = '52b8cfddbe1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_skills',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('major', sa.String(), nullable=True),
        sa.Column('importance', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_market_skills'))
    )
    with op.batch_alter_table('market_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_skills_major'), ['major'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_skills_name'), ['name'], unique=True)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_gaps', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('skills_gaps')

    with op.batch_alter_table('market_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_skills_name'))
        batch_op.drop_index(batch_op.f('ix_market_skills_major'))
        batch_op.drop_index(batch_op.f('ix_market_skills_category'))

    op.drop_table('market_skills')
    # ### end Alembic commands ###
