"""Initial Schema

Revision ID: eb108c90b385
Revises: 
Create Date: 2026-02-04 11:16:50.511147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb108c90b385'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('client_info', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_session_id'), 'resumes', ['session_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('rms_score', sa.Integer(), nullable=True),
    sa.Column('cpi', sa.String(), nullable=True),
    sa.Column('predicted_grad_date', sa.String(), nullable=True),
    sa.Column('skills_detected', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('top_errors', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_index(op.f('ix_resumes_session_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
